import React, { useState } from "react";

const API_BASE_URL = "http://localhost:8000";

interface LogMessage {
  sender: "user" | "agent";
  text: string;
  timestamp: string;
}

export function AI() {
  const [prompt, setPrompt] = useState("");
  const [running, setRunning] = useState(false);
  const [logs, setLogs] = useState<LogMessage[]>([
    {
      sender: "agent",
      text: "Hello! I am your AI Browser Use assistant. Give me a task like 'Research competitors' or 'Monitor pricing pages' and I will operate Chrome to compile insights.",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);

  const handleLaunchAgent = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!prompt.trim()) return;

    const userMsg: LogMessage = {
      sender: "user",
      text: prompt,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };

    setLogs((prev) => [...prev, userMsg]);
    setPrompt("");
    setRunning(true);

    // Simulate launching research agent logs
    const runningMsg: LogMessage = {
      sender: "agent",
      text: "Launching Browser Use agent instance... Spawning headless Chrome.",
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    };
    setLogs((prev) => [...prev, runningMsg]);

    try {
      const response = await fetch(`${API_BASE_URL}/ai/run`, {
        method: "POST"
      });

      if (response.ok) {
        // Simulate execution step logs with delays
        setTimeout(() => {
          setLogs((prev) => [
            ...prev,
            {
              sender: "agent",
              text: "Step 1: Navigated to search engine. Querying competitor products...",
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
            }
          ]);
        }, 1500);

        setTimeout(() => {
          setLogs((prev) => [
            ...prev,
            {
              sender: "agent",
              text: "Step 2: Scraped product matrices and pricing tables. Extracted 4 companies.",
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
            }
          ]);
        }, 3000);

        setTimeout(() => {
          setLogs((prev) => [
            ...prev,
            {
              sender: "agent",
              text: "Execution Completed! Competitive matrix saved to shared Context Feed.",
              timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
            }
          ]);
          setRunning(false);
          
          // Also insert a shared page automatically to simulate Browser Use result share
          fetch(`${API_BASE_URL}/context/share`, {
            method: "POST",
            headers: {
              "Content-Type": "application/json"
            },
            body: JSON.stringify({
              type: "page",
              title: "AI Research: Browser Use Competitor Matrix",
              url: "https://github.com/browser-use/browser-use",
              text_content: "Competitor matrix details generated by AI Agent."
            })
          }).catch(console.error);

        }, 4500);
      }
    } catch (error) {
      setLogs((prev) => [
        ...prev,
        {
          sender: "agent",
          text: "Error starting Browser Use agent process. Please ensure backend is running.",
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
      setRunning(false);
    }
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", height: "calc(100vh - 120px)", gap: "12px" }}>
      {/* Log Console Output */}
      <div
        style={{
          flex: 1,
          backgroundColor: "#0f172a",
          border: "1px solid #334155",
          borderRadius: "8px",
          padding: "12px",
          overflowY: "auto",
          display: "flex",
          flexDirection: "column",
          gap: "10px"
        }}>
        {logs.map((log, idx) => {
          const isUser = log.sender === "user";
          return (
            <div
              key={idx}
              style={{
                alignSelf: isUser ? "flex-end" : "flex-start",
                maxWidth: "85%",
                backgroundColor: isUser ? "#3b82f6" : "#1e293b",
                color: isUser ? "white" : "#e2e8f0",
                padding: "8px 12px",
                borderRadius: isUser ? "12px 12px 0 12px" : "12px 12px 12px 0",
                fontSize: "12px",
                boxShadow: "0 1px 2px rgba(0,0,0,0.1)",
                display: "flex",
                flexDirection: "column",
                gap: "2px"
              }}>
              <div style={{ wordBreak: "break-word", lineHeight: "1.4" }}>{log.text}</div>
              <div style={{ alignSelf: "flex-end", fontSize: "9px", color: isUser ? "#bfdbfe" : "#94a3b8" }}>
                {log.timestamp}
              </div>
            </div>
          );
        })}
      </div>

      {/* Input Form */}
      <form onSubmit={handleLaunchAgent} style={{ display: "flex", gap: "8px" }}>
        <input
          type="text"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="e.g. Research competitor matrices..."
          disabled={running}
          style={{
            flex: 1,
            backgroundColor: "#1e293b",
            color: "white",
            border: "1px solid #334155",
            borderRadius: "6px",
            padding: "8px 12px",
            fontSize: "13px"
          }}
        />
        <button
          type="submit"
          disabled={running || !prompt.trim()}
          style={{
            backgroundColor: running || !prompt.trim() ? "#475569" : "#3b82f6",
            color: "white",
            border: "none",
            borderRadius: "6px",
            padding: "8px 16px",
            fontSize: "12px",
            fontWeight: 600,
            cursor: prompt.trim() ? "pointer" : "default"
          }}>
          {running ? "Running" : "Launch"}
        </button>
      </form>
    </div>
  );
}
